### Задание 1

In [55]:
import numpy as np

In [56]:
a = np.array([[1, 6], [2, 8], [3, 11], [3, 10], [1, 7]])

In [57]:
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [58]:
a.mean(axis=0)

array([2. , 8.4])

In [59]:
mean_a = np.array(a.mean(axis=0))

In [60]:
mean_a

array([2. , 8.4])

### Задание 2

In [61]:
a_centered = a - mean_a

In [62]:
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

### Задание 3

In [63]:
a_centered_sp = a_centered[0:,0] @ a_centered[0:,1]

In [64]:
a_centered_sp

8.0

In [71]:
 a_centered_sp / (4)

2.0

### Задание 4

In [66]:
at = a.T

In [67]:
at

array([[ 1,  2,  3,  3,  1],
       [ 6,  8, 11, 10,  7]])

In [69]:
a_cov = np.cov(at)

In [70]:
a_cov[0,1]

2.0